cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

sudo: true

language: php

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - DB_USERNAME=root
    - SLACK_ENDPOINT=http://myconan.net/null/
    - PATH=$HOME/.yarn/bin:$PATH
    - APP_ENV=testing
    - SESSION_DRIVER=array
    - CACHE_DRIVER=array
    - CAMO_KEY=""

before_install:
  - sudo ./bin/mysql_debian_install
  - nvm install 6.11
  - nvm use 6.11
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - ./bin/db_setup.sh
  - ./build.sh

script: ./bin/phpunit
